### PR TITLE
Merge variables into single file

### LINKED ISSUE #789: Merge variables to single .scss file
I prefer to keep all Sass variables in a single file so you won't have to look through different files to find the variable you are looking for. For example: `text-color` could be in `colors.scss` or in `typography.scss`.

This would look like this:
https://github.com/sboerrigter/pressless/blob/master/assets/styles/abstracts/variables.scss

### PR DESCRIPTION
**Pull request by sboerrigter**
Fixes #789

### CODE REVIEW

**Comment by sboerrigter** [comment]
@haroldangenent I removed the obsolete variables. I decided to keep `$text-font` and remove `$margin-bottom-default`, because `$text-font` is probably going to be used more often when implementing Sphynx.

@luukdv I started this PR before #801 was merged. I will update the variable names when I merge this PR.

**Comment by haroldangenent** [comment]
@sboerrigter Before merging (preferably even before asking acceptance of the PR), I'd recommend merging master into this branch.

**Comment by sboerrigter** [comment]
Done, can you review again?

**Comment by sboerrigter** [comment]
I am sorry. I just reverted my changes and merged master into variables again. I think everything is correct now? Can you please check again?

**Comment by sboerrigter** [comment]
😩

**Pull request closed without merging**
