### PR TITLE
Move information from Wiki to Readme

### LINKED ISSUE #754: Move wiki information to readme
In my opinion, there's not enough information to justify the wiki. Also, you'd be able to see some more info on the 'home' page.

### PR DESCRIPTION
**Pull request by sboerrigter**
Fixes #754. Don't forget to remove the Wiki after this PR is merged.

### CODE REVIEW

**Comment by sboerrigter** [comment]
Don't forget to remove the Wiki after this PR is merged.

**Comment by sboerrigter** [comment]
I think that the image is out of scope. I personally don't really like the image (sorry).

**Comment by luukdv** [comment]
https://github.com/trendwerk/sphynx/issues/754#issuecomment-286430794 we can always replace it when there's something better. 😺

**Comment by sboerrigter** [comment]
I still disagree, but I've added it anyway since it is 2 vs 1.

**Comment by luukdv** [comment]
Nice, but did you properly test this? Because it looks _way_ too big now, with excessive whitespace below and above the image. Was thinking more like https://github.com/kbrsh/moon, don't you agree?

**Comment by haroldangenent** [comment]
I like moon's README header as well. Also [Ava](https://github.com/avajs/ava).

**Comment by sboerrigter** [comment]
You suggested to use the image we currently have, so that is what I did. I agree that is is a bit big, but like you said: we can always replace it when there's something better. 😺

**Comment by luukdv** [comment]
Just remove it and I'll approve.

**Comment by haroldangenent** [comment]
@sboerrigter Can the Wiki be removed now?

**Comment by sboerrigter** [comment]
Yes, I just did. Thanks for the reminder.

**Pull request merged**
